#!/bin/bash

echo "🚀 GitHub HTTPS推送助手"
echo "========================"
echo ""
echo "📋 当前状态:"
git status --short
echo ""
echo "📊 待推送提交:"
git log --oneline origin/main..HEAD
echo ""
echo "🔗 使用Personal Access Token推送:"
echo ""
echo "方法1: 临时推送 (需要输入token)"
echo "git push https://github.com/getAsterisk/claudia.git main"
echo ""
echo "方法2: 设置凭证缓存 (推荐)"
echo "git config --global credential.helper 'cache --timeout=3600'"
echo "git push https://github.com/getAsterisk/claudia.git main"
echo ""
echo "🎯 获取Personal Access Token:"
echo "1. 访问: https://github.com/settings/tokens"
echo "2. 点击 'Generate new token (classic)'"
echo "3. 选择 'repo' 权限"
echo "4. 复制生成的token"
echo "5. 在推送时输入token作为密码"
echo ""
echo "💡 用户名: getAsterisk"
echo "💡 密码: 你的Personal Access Token"
echo ""
echo "🎉 你的Mac Studio M2 Ultra 64GB已准备就绪！"