#!/bin/bash

echo "🚀 GitHub推送助手 - 为你的高配置Mac Studio服务！"
echo "=============================================="
echo ""
echo "方案1: 使用Personal Access Token (推荐)"
echo "1. 访问: https://github.com/settings/tokens"
echo "2. 点击 'Generate new token (classic)'"
echo "3. 选择 'repo' 权限"
echo "4. 复制生成的token"
echo "5. 运行以下命令推送:"
echo ""
echo "git push https://你的token@github.com/getAsterisk/claudia.git main"
echo ""
echo "=============================================="
echo ""
echo "方案2: 添加SSH密钥到GitHub"
echo "1. 复制以下SSH公钥:"
echo ""
cat ~/.ssh/id_ed25519.pub
echo ""
echo "2. 访问: https://github.com/settings/ssh"
echo "3. 点击 'New SSH key'"
echo "4. 粘贴上面的公钥"
echo "5. 保存后运行: git push origin main"
echo ""
echo "=============================================="
echo ""
echo "当前项目状态:"
git status --short
echo ""
echo "准备推送的文件数量: $(git diff --cached --name-only | wc -l)"
echo "你的高配置Mac Studio M2 Ultra 64GB已准备就绪！💪"